version: '3.8'
networks:
  web:
    external: true
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: db-taraga
    environment:
      - POSTGRES_USER=taraga
      - POSTGRES_PASSWORD=Lula@10203040
    labels:
      - traefik.http.routers.site-taraga.rule=Host(`db.taraga.tech`)
      - traefik.http.routers.site-taraga.tls=true
      - traefik.http.routers.site-taraga.tls.certresolver=lets-encrypt
      - traefik.port=5432  
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - web
volumes:
  db:
    driver: local